const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'Nik-Slim-Shirt',
      category: 'shirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality branded Nike shirt, ideal for Men',
    },
    {
      name: 'Metal Mobile Stand',
      slug: 'Metal-Mobile-Stand',
      category: 'accessories',
      image: '/images/p3.jpg',
      price: 90,
      countInStock: 220,
      brand: 'Unknown',
      rating: 3.5,
      numReviews: 23,
      description: 'High quality multipurpose Mobile holder',
    },
    {
      name: 'Manyavar Slim Shirt',
      slug: 'Manyavar-Slim-Shirt',
      category: 'shirt',
      image: '/images/p2.jpg',
      price: 220,
      countInStock: 4,
      brand: 'Manyavar',
      rating: 4.8,
      numReviews: 15,
      description: 'High quality branded Manyavar shirt, ideal for Groom',
    },
    {
      name: 'Deep Base headphone',
      slug: 'Deep-Base-headphone',
      category: 'accessories',
      image: '/images/p4.jpg',
      price: 590,
      countInStock: 3,
      brand: 'Boat',
      rating: 4.3,
      numReviews: 233,
      description: 'High quality headsets for Gamming and streeming',
    },
  ],
};

export default data;
